name: 'Upload Episode from YouTube To Spotify for Podcasters'

on:
  workflow_dispatch:
    inputs:
      video_id:
        description: 'Enter YouTube video ID to upload on Spotify for Podcasters.'
        required: true

jobs:
  upload_episode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Create episode.json file
        run: |
          video_id="${{ github.event.inputs.video_id }}"
          json_content="{\"id\": \"${video_id}\"}"
          echo "${json_content}" > episode.json
          cat episode.json
      - name: Upload Episode from YouTube To Spotify for Podcasters
        uses: Schroedinger-Hat/youtube-to-spotify@fa5499eb095245c6a93ea2993e71211717a381cc # main
        env:
          SPOTIFY_EMAIL: ${{ secrets.SPOTIFY_EMAIL }}
          SPOTIFY_PASSWORD: ${{ secrets.SPOTIFY_PASSWORD }}
          EPISODE_PATH: /github/workspace
          URL_IN_DESCRIPTION: true
          LOAD_THUMBNAIL: true
          POSTPROCESSOR_ARGS: 'ExtractAudio+ffmpeg:-ac 1'
